[package]
name = "rusty-trades"
version = "0.1.0"
authors = ["skor <olek.skoryk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4"
rand = "0.8"
regex = "1.5"